name: Build Firefox on Linux

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3

      - name: Free up Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

      - name: Bootstrap Mozilla Source
        run: |
          curl https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -O
          python3 bootstrap.py --application-choice=browser --no-interactive

      - name: Update Local Source
        working-directory: ./mozilla-unified
        run: bash $GITHUB_WORKSPACE/version.sh | xargs hg up -C

      - name: Initialize `mozconfig`
        working-directory: ./mozilla-unified
        run: |
          echo 'ac_add_options --with-branding=browser/branding/unofficial' > mozconfig
          echo 'ac_add_options --disable-updater' >> mozconfig
          echo 'ac_add_options --disable-tests' >> mozconfig
          echo 'ac_add_options --disable-crashreporter' >> mozconfig
          bash $GITHUB_WORKSPACE/patch.sh

      - name: Build and Package
        working-directory: ./mozilla-unified
        run: |
          ./mach build 
          ./mach package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-firefox-amd64
          path: "**/*.tar.bz2"
