name: Build Firefox on macOS(apple)

on:
  # push:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  build:
    runs-on: "macos-13"
    permissions:
      contents: write
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3

      - name: Install Mercurial
        run: python3 -m pip install mercurial==6.1.4

      - name: Bootstrap Mozilla Source
        run: |
          curl https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -O
          python3 bootstrap.py --application-choice=browser --no-interactive

      - name: Update Local Source
        working-directory: ./mozilla-unified
        run: bash $GITHUB_WORKSPACE/version.sh | xargs hg up -C

      - name: Initialize `mozconfig`
        working-directory: ./mozilla-unified
        run: |
          cat $GITHUB_WORKSPACE/mozconfig > mozconfig
          echo 'export CC="$HOME"/.mozbuild/clang/bin/clang' >> mozconfig
          echo 'export CXX="$HOME"/.mozbuild/clang/bin/clang++' >> mozconfig
          echo 'ac_add_options --target=aarch64-apple-darwin' >> mozconfig
          rustup target add aarch64-apple-darwin
          bash $GITHUB_WORKSPACE/patch.sh

      - name: Build and Package
        working-directory: ./mozilla-unified
        run: |
          ./mach build 
          ./mach package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-firefox-arm64
          path: "**/*.dmg"
