name: Build Firefox on macOS(Intel)

on:
  push:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  build:
    runs-on: "macos-14"
    permissions:
      contents: write
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: Install Mercurial
        run: |
          echo "version=$(bash $GITHUB_WORKSPACE/version.sh)" >> $GITHUB_ENV
          brew update
          brew install --force --overwrite python@3.12
          brew link --overwrite python@3.12
          brew install --force --overwrite python@3.11
          brew link --overwrite python@3.11

      - name: Bootstrap Mozilla Source
        run: |
          git clone --depth 1 --branch $version https://github.com/mozilla/gecko-dev mozilla-unified

      - name: Initialize `mozconfig`
        working-directory: ./mozilla-unified
        run: |
          bash $GITHUB_WORKSPACE/patch.sh

      - name: Build and Package
        working-directory: ./mozilla-unified
        run: |
          ./mach --no-interactive bootstrap --application-choice=browser
          ./mach build 
          ./mach package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-firefox-${{ env.version }}-amd64
          path: "**/*.dmg"
