name: Build Firefox on macOS(Apple_silicon)

on:
  # push:
  schedule:
    - cron: '0 0 3 * *'

jobs:
  build:
    runs-on: "macos-latest"
    permissions:
      contents: write
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: Install Mercurial
        run: |
          echo "version=$(bash $GITHUB_WORKSPACE/version.sh)" >> $GITHUB_ENV
          brew update
          brew install nasm

      - name: Bootstrap Mozilla Source
        run: |
          git clone --depth 1 --branch $version https://github.com/mozilla/gecko-dev mozilla-unified

      - name: Initialize `mozconfig`
        working-directory: ./mozilla-unified
        run: |
          bash $GITHUB_WORKSPACE/patch.sh
          echo 'ac_add_options --target=aarch64-apple-darwin' >> mozconfig
          rustup target add aarch64-apple-darwin

      - name: Build and Package
        working-directory: ./mozilla-unified
        run: |
          ./mach --no-interactive bootstrap --application-choice=browser
          ./mach build 
          ./mach package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-firefox-${{ env.version }}-arm64
          path: "**/*.dmg"
